SELECT * FROM SYSCAT.TABLES WHERE TABNAME = 'TEST';
SELECT * FROM SYSIBM.SYSTABLES WHERE CREATOR = 'DB2INST1';

CREATE TABLE TEST (ID INT NOT NULL PRIMARY KEY,NAME VARCHAR(100),AGE INT);

INSERT INTO TEST (ID, NAME, AGE) VALUES (1, 'John Doe', 30);
INSERT INTO TEST (ID, NAME, AGE) VALUES (2, '123456', 30);

SELECT * FROM TEST;
